name: Rust

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**.rs'
      - 'tests/**'
      - 'Cargo.toml'
      - 'valgrind.supp'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**.rs'
      - 'tests/**'
      - 'Cargo.toml'
      - 'valgrind.supp'
jobs:
  check:
    if: github.event.pull_request.draft == false
    uses: DoumanAsh/douman-ci/.github/workflows/rust.yml@master
    with:
      runs-on: ubuntu-latest
      min-rustc-version: "1.63.0"
